import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import Header from "../components/Header";
import "./globals.css";

const neulisNeue = localFont({
  src: [
    { path: "../../public/fonts/fonnts.com-Neulis_Neue_Bold_Italic.otf", weight: "700", style: "italic" },
    { path: "../../public/fonts/fonnts.com-Neulis_Neue_Bold.otf", weight: "700", style: "normal" },
    { path: "../../public/fonts/fonnts.com-Neulis_Neue_Italic.otf", weight: "400", style: "italic" },
    { path: "../../public/fonts/fonnts.com-Neulis_Neue_Regular.otf", weight: "400", style: "normal" },
    { path: "../../public/fonts/fonnts.com-Neulis_Neue_Medium_Italic.otf", weight: "500", style: "italic" },
    { path: "../../public/fonts/fonnts.com-Neulis_Neue_Medium.otf", weight: "500", style: "normal" },
  ],
  variable: "--font-neulis-neue",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${neulisNeue.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system">

          {children}

        </ThemeProvider>
      </body>
    </html>
  );
}
