import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const clashGrotesk = localFont({
  src: [
    { path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Bold.woff", weight: "700", style: "normal" },
    { path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Semibold.woff", weight: "600", style: "normal" },
    { path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Medium.woff", weight: "500", style: "normal" },
    { path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Regular.woff", weight: "400", style: "normal" },
    { path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Light.woff", weight: "300", style: "normal", },
    { path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Variable.woff", weight: "100 900", style: "normal" }

  ],
  variable: "--font-clash-grotesk",
  display: "swap"
});
const tabular = localFont({
  src: [
    { path: "../../public/fonts/Tabular/Tabular-BoldItalic.woff", weight: "700", style: "italic" },
    { path: "../../public/fonts/Tabular/Tabular-Bold.woff", weight: "700", style: "normal" },
    { path: "../../public/fonts/Tabular/Tabular-Italic.woff", weight: "400", style: "italic" },
    { path: "../../public/fonts/Tabular/Tabular-Regular.woff", weight: "400", style: "normal" },
    { path: "../../public/fonts/Tabular/Tabular-MediumItalic.woff", weight: "500", style: "italic" },
    { path: "../../public/fonts/Tabular/Tabular-Medium.woff", weight: "500", style: "normal" },

  ],
  variable: "--font-tabular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${clashGrotesk.variable} ${tabular.variable} antialiased `} >
        {children}
      </body>
    </html>
  );
}
